=== OmkarMirgal/XML/deliveries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:myspace:deliveries" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:myspace:deliveries" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="deliveries">
     <xs:complexType>
         <xs:sequence maxOccurs="unbounded">
             <xs:element ref="article"/>
         </xs:sequence>
     </xs:complexType>
 </xs:element>
 <xs:element name="article">
     <xs:complexType>
         <xs:all>
             <xs:element name="name" type="xs:string"/>
             <xs:element name="price" type="price_type"/>
             <xs:element name="supplier" type="xs:string"/>
         </xs:all>
         <xs:attribute name="id" type="xs:integer" use="required"/>
     </xs:complexType>
 </xs:element>
 <xs:complexType name="price_type">
     <xs:simpleContent>
         <xs:extension base="xs:double">
             <xs:attribute name="unitprice" type="xs:boolean"/>
         </xs:extension>
     </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== OmkarMirgal/XML/Task6/fixed_deliveries.xml
<?xml version="1.0" encoding="UTF-8"?>
<deliveries xmlns="urn:myspace:deliveries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:myspace:deliveries ../deliveries.xsd">
   <article id='3526'>
      <name>apple</name>
      <price>8.97</price>
      <supplier>Krause Inc.</supplier>
   </article>
   <article id='7866'>
      <name>cherries</name>
      <price>10.45</price>
      <supplier>Helbig Inc.</supplier>
   </article>
   <article id='4444'>
      <name>apple</name>
      <price>12.67</price>
      <supplier>Liebig Inc.</supplier>
   </article>
   <article id='7868'>
      <name>cabbage</name>
      <price>3.20</price>
      <supplier>Hoeller Inc.</supplier>
   </article>
   <article id='3245'>
      <name>bpineapple</name>
      <price>15.67</price>
      <supplier>Hoeller Inc.</supplier>
   </article>
   <article id='6745'>
      <name>cabbage</name>
      <price>3.10</price>
      <supplier>Reinhardt Inc.</supplier>
   </article>
   <article id='7789'>
      <name>pineapple</name>
      <price>8.60</price>
      <supplier>Richard Inc.</supplier>
   </article>
   <article id='38462'>
      <name>cherries</name>
      <price>17.67</price>
      <supplier>Krause Inc.</supplier>
   </article>
   <article id='18632'>
      <name>cherries</name>
      <price>16.45</price>
      <supplier>Hoeller Inc.</supplier>
   </article>
   <article id='25454'>
      <name>cherries</name>
      <price>12.45</price>
      <supplier>Richard Inc.</supplier>
   </article>
   <article id='78832'>
      <name>apple</name>
      <price>9.54</price>
      <supplier>Mertes Inc.</supplier>
   </article>
</deliveries>

=== OmkarMirgal/XML/Task3/duplicate_deliveries.xml
<?xml version="1.0" encoding="UTF-8"?>
<deliveries xmlns="urn:myspace:deliveries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:myspace:deliveries ../deliveries.xsd">
<article id='7866'>
   <name>cherries</name>
   <price>17.67</price>
   <supplier>Krause Inc.</supplier>
</article>
<article id='3526'>
   <name>apple</name>
   <price>9.54</price>
   <supplier>Mertes Inc.</supplier>
</article>
<article id='7866'>
   <name>cherries</name>
   <price>16.45</price>
   <supplier>Hoeller Inc.</supplier>
</article>
<article id='7866'>
   <name>cherries</name>
   <price>12.45</price>
   <supplier>Richard Inc.</supplier>
</article>
</deliveries>

=== OmkarMirgal/XML/Task3/Task_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Task_3.xsl"?>
<deliveries xmlns="urn:myspace:deliveries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:myspace:deliveries ../Task2/deliveries.xsd">
 <article id="3526">
     <name>apple</name>
     <price unitprice="true">8.97</price>
     <supplier>Krause Inc.</supplier>
 </article>
 <article id="7866">
     <name>cherries</name>
     <price unitprice="false">10.45</price>
     <supplier>Helbig Inc.</supplier>
 </article>
 <article id="4444">
     <name>apple</name>
     <price unitprice="true">12.67</price>
     <supplier>Liebig Inc.</supplier>
 </article>
 <article id="7866">
     <name>cherries</name>
     <price >17.67</price>
     <supplier>Krause Inc.</supplier>
 </article>
 <article id="3526">
     <name>apple</name>
     <price unitprice="true">9.54</price>
     <supplier>Mertes Inc.</supplier>
 </article>
 <article id="7866">
     <name>cherries</name>
     <price unitprice="false">16.45</price>
     <supplier>Hoeller Inc.</supplier>
 </article>
 <article id="7868">
     <name>cabbage</name>
     <price unitprice="false">3.20</price>
     <supplier>Hoeller Inc.</supplier>
 </article>
 <article id="7866">
     <name>cherries</name>
     <price unitprice="false">12.45</price>
     <supplier>Richard Inc.</supplier>
 </article>
 <article id="3245">
     <name>bpineapple</name>
     <price unitprice="false">15.67</price>
     <supplier>Hoeller Inc.</supplier>
 </article>
 <article id="6745">
     <name>cabbage</name>
     <price unitprice="false">3.10</price>
     <supplier>Reinhardt Inc.</supplier>
 </article>
 <article id="7789">
     <name>pineapple</name>
     <price unitprice="true">8.60</price>
     <supplier>Richard Inc.</supplier>
 </article>
</deliveries>
